// <auto-generated />
namespace JetSpring.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class att2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(att2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903070433216_att2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
